### PR TITLE
applied share-this to all p tags; added share-this css to webpack

### PR DESCRIPTION
**Pull request by seangtkelley**

### CODE REVIEW

**Comment by ben-pr-p** [comment]
Good code, bad git tree – let's see how we can fix this

**Comment by ben-pr-p** [comment]
Seems like your `add/platform-page` had a bunch more commits from `master` than `BrandNewCongress/core/add/platform-page`. I think merging `master` into this `add/platform-page` might fix it

**Comment by seangtkelley** [comment]
Definitely. I'll do that now

**Comment by ben-pr-p** [comment]
Wait, sorry – let's talk about this in Slack – I just merged master to `add/platform-page`

**Pull request closed without merging**
