### PR TITLE
Add/platform page

### PR DESCRIPTION
**Pull request by seangtkelley**

### CODE REVIEW

**Comment by ben-pr-p** [comment]
Thanks for the PR! 

Let's get the font sizes right, bold on the `plank-title`'s, dashed border underneath the `platform-item-title`'s, and also the proper styling with `localhost:4000/platform?brand=jd`. I've marked those platform areas that we're currently rendering for BNC to render for JD as well. 

After that, we'll merge and then move onto dynamically generating the sitemap

**Comment by seangtkelley** [comment]
So, just to make sure I understand, `localhost:4000/platform?brand=jd` should have different css to make it look like `https://justicedemocrats.com/Platform`?

**Comment by ben-pr-p** [comment]
Exactly, yeah – there logic for getting different styles based on domain name / `brand=` is already there.

If there's no `brand=` or `brand=bnc`, the body will have a class `bnc`. If it's `brand=jd`, the body will have a class `jd`. So you can do your 
```
.jd p {
  font-family: /* something */
}
```

**Comment by ben-pr-p** [comment]
`?brand=bnc` looks perfect – let's get rid of the orange stars with `?brand=jd` and then we're good to go 🥇

**Comment by seangtkelley** [comment]
How does it look now? I removed the stars from `?brand=jd` and did some minor styling tweaks.

**Comment by ben-pr-p** [comment]
Thanks so much Sean!

**Pull request merged**
